services:
  k9_random_data_api_blue:
    build: .
    expose:
      - "5000"
    networks:
      flask_network:
        ipv4_address: 172.19.0.2

  k9_random_data_api_green:
    build: .
    expose:
      - "5000"
    networks:
      flask_network:
        ipv4_address: 172.19.0.3

networks:
  flask_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24