version: '3.8'

services:
  app:
    build: .
    environment:
      - PORT=5000  # Bind to port 5000 inside the container
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
    ports:
      - "5001:5000"  # Map container port 5000 to host port 5001
      - "5002:5000"  # For the second instance, map container port 5000 to host port 5002