version: '3.8'

services:
  app:
    build: .
    environment:
      - PORT=5000
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
    ports:
      - "5000"
      - "5001"