version: '3.8'

services:
  app:
    build: .
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first  # Start the new container before stopping the old one
    ports:
      - "5001:5000"
      - "5002:5000"
    environment:
      - PORT=5000