version: '3.8'

services:
  k9_random_data_api:
    build: .
    expose:
      - "5000"
    environment:
      - PORT=5000
    networks:
      - flask_network

networks:
  flask_network:
    driver: bridge