networks:
  flask_network:
    driver: bridge


services:
  k9_random_data_api:
    build: .
    deploy:
      replicas: 2
    expose:
      - "5000"
    environment:
      - PORT=5000
    networks:
      - flask_network